# Configuration du moteur de pertinence

thresholds:
  intervene: 0.5
  observe: 0.0

factor_weights:
  expertise_match: 0.3
  conversation_gap: 0.25
  workload_capacity: 0.2
  recent_participation: 0.15
  relationship_trust: 0.05
  timing_appropriateness: 0.05